/*
 * This file was generated by the Gradle 'init' task.
 */
//
//pluginManagement {
//    repositories {
//        gradlePluginPortal()
//        maven("https://raw.githubusercontent.com/kotlin-graphics/mary/master")
//    }
//}
//
//enableFeaturePreview("VERSION_CATALOGS")
//
//plugins {
//    id("sciJava.catalogs") version "30.0.0+66"
//}

rootProject.name = "insitu"

includeBuild("../scenery")