if (vis && step > localNear && step < localFar)
{
    transparentSample = false;
    vec4 x = sampleVolume(wpos);

//    #if USE_PRINTF
//    if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//        debugPrintfEXT("Step: %d, color of sample: (%f, %f, %f, %f) at position: (%f, %f, %f, %f)", i, x.rgba, wpos.xyzw);
//    }
//    #endif

    if(x.r > -0.5 || lastSample) { // we need to process this sample only if it is from a volume that actually exists at this sample point
//        #if USE_PRINTF
//        if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//            debugPrintfEXT("Step: %d, color of sample: (%f, %f, %f, %f) at position: (%f, %f, %f, %f)", i, x.rgba, wpos.xyzw);
//        }
//        #endif

        float newAlpha = x.a;
        vec3 newColor = x.rgb;

        if(newAlpha <= minOpacity) {
            transparentSample = true;
        } else {
            w_prev_non_transp = wpos;
//            w_prev_non_transp = wprev;
            ndcPos = pv * wpos;
            ndcPos *= 1. / ndcPos.w;
            ndc_step = ndcPos.z;
        }

//        #if USE_PRINTF
//        if(gl_GlobalInvocationID.xy == debug_pixel && lastSample) {
//            debugPrintfEXT("lastsample is: (%f, %f, %f, %f). Is transparent? %d", x.rgba, transparentSample);
//        }
//        #endif

        if(supersegmentIsOpen) {

            //        imageStore(OutputSubVDIColor, ivec3(3 * supersegmentNum + 1, gl_GlobalInvocationID.y, gl_GlobalInvocationID.x), vec4(0));
            //        imageStore(OutputSubVDIColor, ivec3(3 * supersegmentNum + 2, gl_GlobalInvocationID.y, gl_GlobalInvocationID.x), vec4(0));
            //        imageStore(OutputSubVDIColor, ivec3(3 * supersegmentNum, gl_GlobalInvocationID.y, gl_GlobalInvocationID.x), vec4(0));
            //        supersegmentNum++;

            //        float segLen = step - supSegStartPoint;
            //        float segLen = ndc_step - supSegStartPoint;
//            float segLen = length(wprev - supseg_start_w);
//            #if USE_PRINTF
//            if(gl_GlobalInvocationID.xy == debug_pixel &&  (w_prev_non_transp != wprev) && thresh_found) {
//                debugPrintfEXT("Supseg_num: %d. w_prev_non_transp: (%f, %f, %f, %f), wprev: (%f, %f, %f, %f).", supersegmentNum, w_prev_non_transp.xyzw, wprev.xyzw);
//            }
//            #endif

            vec4 jump_pos = mix(wfront, wback, nw * steps_in_supseg); //TODO: jump length of single step can be precalculated and scaled to num steps in supseg

            float segLen = length(jump_pos - wfront);
            supersegmentAdjusted.rgb = curV.rgb / curV.a;
            supersegmentAdjusted.a = adjustOpacity(curV.a, 1.0/segLen);
            //        supersegmentAdjusted.a = curV.a;
            //        supersegmentAdjusted = x;
            float diff = diffPremultiplied(supersegmentAdjusted, x);

            bool newSupSeg = false;
            if(diff >= newSupSegThresh) {
                newSupSeg = true;
//                #if USE_PRINTF
//                if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//                    debugPrintfEXT("Termination criteria reached for %dth time, color of supseg was: (%f, %f, %f, %f)", num_terminations, supersegmentAdjusted.rgba);
//                }
//                #endif
            }

            if((newSupSeg && !(lastSupersegment))) { //closing a supersegment
                num_terminations++;
//                #if USE_PRINTF
//                if(gl_GlobalInvocationID.xy == debug_pixel) {
//                    debugPrintfEXT("Closing supseg");
//                }
//                #endif
                supersegmentIsOpen = false;
                //            supSegEndPoint = step;

                #if WORLD_ABS
                vec3 diff = w_prev_non_transp.xyz - ro_world.xyz;
                if(!(abs(rd_world.x) < 0.05)) {
                    supSegEndPoint = diff.x / (rd_world.x);
                } else if (!(abs(rd_world.y) < 0.05)) {
                    supSegEndPoint = diff.y / (rd_world.y);
                } else {
                    supSegEndPoint = diff.z / (rd_world.z);
                }
                #else
                    #if INT_DEPTHS
//                    #if USE_PRINTF
//                    if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//                        debugPrintfEXT("Supseg: %d. Recording end point as : %d. ndc at this stage: %f", supersegmentNum, (supSegStartPoint + steps_in_supseg), ndc_step);
//                    }
//                    #endif
                    supSegEndPoint = supSegStartPoint + steps_in_supseg;
                    #else
                    supSegEndPoint = ndc_step;
                    #endif
                #endif
                steps_in_supseg = 0;

                if(thresh_found) {

                    writeSupersegment(supersegmentNum, supSegStartPoint, supSegEndPoint, supersegmentAdjusted);

                    #if INT_DEPTHS
                    float start_step = tnear + nw * supSegStartPoint;
                    vec4 start_w = mix(wfront, wback, start_step);
                    vec4 start_v = ViewMatrices[0] * start_w;

                    float end_step = tnear + nw * supSegEndPoint;
                    vec4 end_w = mix(wfront, wback, end_step);
                    vec4 end_v = ViewMatrices[0] * end_w;

                    int start_cell = findZInterval_view(start_v.z);
                    int end_cell = findZInterval_view(end_v.z);

                    for(int j = start_cell; j <= end_cell; j++) {
                        grid_cell.z = j;
                        update_cell_count(grid_cell);
                    }
                    #endif

                    supersegmentNum++;
                }
            }
        }

//        if( (!lastSample) && (!supersegmentIsOpen) && (!transparentSample) ) { //opening a supersegment
        if( (!supersegmentIsOpen) && (!transparentSample) ) { //opening a supersegment

//            #if USE_PRINTF
//            if(gl_GlobalInvocationID.xy == debug_pixel) {
//                debugPrintfEXT("Opening supseg: %d. Sample value was: (%f, %f, %f, %f). Step number: %d", supersegmentNum, x.rgba, i);
//            }
//            #endif

            supersegmentIsOpen = true;
            //        supSegStartPoint = step;
            #if WORLD_ABS
            vec3 diff = w_prev_non_transp.xyz - ro_world.xyz;
            if(!(abs(rd_world.x) < 0.05)) {
                supSegStartPoint = diff.x / (rd_world.x);
            } else if (!(abs(rd_world.y) < 0.05)) {
                supSegStartPoint = diff.y / (rd_world.y);
            } else {
                supSegStartPoint = diff.z / (rd_world.z);
            }
            #else
                #if INT_DEPTHS
                #if USE_PRINTF
                if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
                    debugPrintfEXT("Supseg: %d. Recording start point as : %d. ndc at this stage: %f", supersegmentNum, i, ndc_step);
                }
                #endif

                supSegStartPoint = i;
                #else
                supSegStartPoint = ndc_step;
                #endif
            #endif
            supseg_start_w = wpos;
            curV = vec4( 0 );
        }

//        if(!transparentSample) {
            float w = adjustOpacity(newAlpha, length(wpos - wprev)); //TODO: jump length can be precalculated

            if(supersegmentIsOpen) {

                //    float w = newAlpha;
                curV.rgb = curV.rgb + (1 - curV.a) * newColor * w;
                curV.a = curV.a + (1 - curV.a) * w;

                steps_in_supseg++;
            }

            v.rgb = v.rgb + (1.0f - v.a) * newColor * w; //TODO Remove
            v.a = v.a + (1.0f - v.a) * w;

//            #if USE_PRINTF
//            if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//                debugPrintfEXT("Step: %d. Accumulated color so far: (%f, %f, %f, %f)", i, v);
//            }
//            #endif


            if(lastSample && supersegmentIsOpen) { //close the supersegment after the last sample is accumulated

                vec4 jump_pos = mix(wfront, wback, nw * steps_in_supseg);

                float segLen = length(jump_pos - wfront);
                supersegmentAdjusted.rgb = curV.rgb / curV.a;
                supersegmentAdjusted.a = adjustOpacity(curV.a, 1.0/segLen);

                num_terminations++;
//                #if USE_PRINTF
//                if(gl_GlobalInvocationID.xy == debug_pixel) {
//                    debugPrintfEXT("Closing supseg");
//                }
//                #endif
                supersegmentIsOpen = false;
                //            supSegEndPoint = step;

                #if WORLD_ABS
                vec3 diff = w_prev_non_transp.xyz - ro_world.xyz;
                if(!(abs(rd_world.x) < 0.05)) {
                    supSegEndPoint = diff.x / (rd_world.x);
                } else if (!(abs(rd_world.y) < 0.05)) {
                    supSegEndPoint = diff.y / (rd_world.y);
                } else {
                    supSegEndPoint = diff.z / (rd_world.z);
                }
                #else
                    #if INT_DEPTHS
                    supSegEndPoint = supSegStartPoint + steps_in_supseg;
                    #else
                    supSegEndPoint = ndc_step;
                    #endif
                #endif
                steps_in_supseg = 0;

                if(thresh_found) {

                    writeSupersegment(supersegmentNum, supSegStartPoint, supSegEndPoint, supersegmentAdjusted);

                    #if INT_DEPTHS
                    float start_step = tnear + nw * supSegStartPoint;
                    vec4 start_w = mix(wfront, wback, start_step);
                    vec4 start_v = ViewMatrices[0] * start_w;

                    float end_step = tnear + nw * supSegEndPoint;
                    vec4 end_w = mix(wfront, wback, end_step);
                    vec4 end_v = ViewMatrices[0] * end_w;

                    int start_cell = findZInterval_view(start_v.z);
                    int end_cell = findZInterval_view(end_v.z);

                    for(int j = start_cell; j <= end_cell; j++) {
                        grid_cell.z = j;
                        update_cell_count(grid_cell);
                    }
                    #endif

                    supersegmentNum++;
                }
            }

//            #if USE_PRINTF
//            if(gl_GlobalInvocationID.xy == debug_pixel && thresh_found) {
//                debugPrintfEXT("Accumulated so far: within supseg: (%f, %f, %f, %f) overall: (%f, %f, %f, %f)", curV.rgba, v.rgba);
//            }
//            #endif
//        }


        //    if(v.a >= 1.0f) {
        //        break;
        //    }

    }
}
